micronaut:
  application:
    name: rhe-sync
  server:
    port: ${SERVER_PORT:8080}
    netty:
      access-logger:
        enabled: true # Enables the access logger
        logger-name: access-logger # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
        log-format: common # A log format, optional, default is Common Log Format
        exclusions:
          - /favicon.ico
          - /health
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db_rhe_prod`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:f3rr31r0}
    driver-class-name: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
    db-type: mysql
    dialect: MYSQL
flyway:
  datasources:
    default:
      locations: classpath:db/migration/mysql
      url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db_rhe_prod`}
      username: ${JDBC_USER:root}
      password: ${JDBC_PASSWORD:f3rr31r0}
      enabled: true
      table: schema_version
jobrunr:
  background-job-server:
    enabled: false
  dashboard:
    enabled: false
jpa.default.properties.hibernate.hbm2ddl.auto: none
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    entity-scan.packages: br.rs.gov.defensoria.rhe.entity.jpa
logger:
  levels:
    root: DEBUG
    #    io: TRACE
    # io: DEBUG
#      micronaut:
#        context:
#          condition: TRACE
worker:
  jobs:
    sync:
      local-files-dir: D:\MIG\DPE\DEV\file
      aborted-dir: aborted\
      normal-dir: normalized\
      normal-waiting-dir: normalized-waiting\
      rsync-dir: rsync\
      sended-dir: sended\
      raw-waiting-dir: waiting\
      logs-dir: log\
      notification-dir: notification\
