micronaut:
  application:
    name: rhe-sync
    version: ${APP_VERSION:undefined}
  server:
    port: ${SERVER_PORT:8080}
    netty:
      access-logger:
        enabled: true # Enables the access logger
        logger-name: access-logger # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
        log-format: common # A log format, optional, default is Common Log Format
        exclusions:
          - /favicon.ico
          - /health
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://172.28.144.1:3306/db_rhe_prod`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:f3rr31r0}
    driver-class-name: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
    db-type: mysql
    dialect: MYSQL
flyway:
  datasources:
    default:
      locations: classpath:db/migration/mysql
      url: ${JDBC_URL:`jdbc:mysql://172.28.144.1:3306/db_rhe_prod`}
      username: ${JDBC_USER:root}
      password: ${JDBC_PASSWORD:f3rr31r0}
      enabled: true
      table: schema_version
jobrunr:
  background-job-server:
    enabled: false
  dashboard:
    enabled: false
jpa.default.properties.hibernate.hbm2ddl.auto: none
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
    entity-scan.packages: br.rs.gov.defensoria.rhe.entity.jpa
logger:
  levels:
    root: DEBUG
worker:
  jobs:
    sync:
      local-files-dir: /app/files/
      aborted-dir: aborted/
      normal-dir: normalized/
      normal-waiting-dir: normalized-waiting/
      rsync-dir: rsync/
      sended-dir: sended/
      raw-waiting-dir: waiting/
      logs-dir: log/
      notification-dir: notification/
    notification:
      email-from: adm-info@defensoria.rs.def.br
      email-to: eder-soares@defensoria.rs.def.br
      email-var-status: %_status_%
      email-subject: Rhe-Sync[%_status_%]
javamail:
  protocol: smtp
  properties.mail.smtp:
    default-encoding: UTF-8
    from: "adm-info@defensoria.rs.def.br"
    host: smtp-infra.defpub.local
    port: 25
    auth: false
    starttls.enable: false