CREATE TABLE rhe_dados_dependentes(
    id_funcional varchar(50) NOT NULL,
    id_funcional_dependente varchar(50) NULL,
    nr_pens varchar(50) NULL,
    nr_dependente varchar(50) NOT NULL,
    nrcpf varchar(50) NULL,
    no_dependente varchar(50) NULL,
    no_parentesco varchar(50) NULL,
    dt_nascimento date NULL,
    cd_sexo varchar(5) NULL,
    dt_inicio date NULL,
    dt_termino date NULL,
    no_estado_civil varchar(50) NULL,
    fg_estudante varchar(2) NULL,
    fg_universitario varchar(2) NULL,
    fg_invalido varchar(2) NULL,
    fg_excepcional varchar(2) NULL,
    no_tipo_invalidez varchar(50) NULL,
    no_tipo_excepcional varchar(50) NULL,
    nr_rg varchar(50) NULL,
    tp_rg varchar(50) NULL,
    de_orgao_rg varchar(50) NULL,
    cd_uf_rg varchar(50) NULL,
    dt_expedicao_rg varchar(50) NULL,
    tp_doc_certnc varchar(50) NULL,
    nr_certnc varchar(50) NULL,
    nr_livro_certnc varchar(50) NULL,
    nr_folha_certnc varchar(50) NULL,
    nr_cartorio_certnc varchar(255) NULL,
    cd_uf_certnc varchar(50) NULL,
    cd_municipio_certnc varchar(50) NULL,
    nr_matricula_certnc varchar(50) NULL,
    tp_doc_certod varchar(50) NULL,
    dt_certod varchar(50) NULL,
    nr_certod varchar(50) NULL,
    nr_livro_certod varchar(50) NULL,
    nr_folha_certod varchar(50) NULL,
    nr_cartoriio_certod varchar(50) NULL,
    cd_uf_certod varchar(50) NULL,
    cd_municipio_certod varchar(50) NULL,
    nd_matricula_certod varchar(50) NULL,
    regra_alimentado varchar(50) NULL,
    CREATED datetime DEFAULT NULL,
    LASTUPDATED datetime DEFAULT NULL,
    PRIMARY KEY  (id_funcional,nr_dependente)
);